name: Get Patch Apps Info

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"  # Replace with your desired Python version

      - name: Install dependencies
        run: pip install -r apps/requirements.txt
        
      - name: Update py_file_url
        run: |
          sed -i 's@py_file_url = "https://raw.githubusercontent.com/.*@py_file_url = "https://raw.githubusercontent.com/${{ github.repository }}/main/src/patches.py"@' apps/apps.py
          sed -i 's@config_py_file_url = "https://raw.githubusercontent.com/.*@config_py_file_url = "https://raw.githubusercontent.com/${{ github.repository }}/main/src/config.py"@' apps/apps.py
        
      - name: Set up Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Set up ChromeDriver
        run: |
          wget -N https://chromedriver.storage.googleapis.com/94.0.4606.41/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver 
        
      - name: Run Python script
        run: python apps/apps.py
        
      - name: Commit and push changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add generated files - apps.json, apps.md"
          git push
