name: Delete Releases and Tags

on:
  workflow_dispatch:

jobs:
  delete-releases-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete releases and tags
        run: |
          gh release list --limit 100 | awk '{print $1}' | xargs -I {} gh release delete {}
          if [[ -n "$(git tag -l)" ]]; then git tag -d $(git tag -l); fi

      - name: Push tag deletion changes
        run: |
          if [[ -n "$(git tag -l)" ]]; then git fetch --prune --tags; git push origin --delete $(git tag -l); fi

      - name: Push updated tags
        run: |
          git push --tags --force
