name: Scheduled Update Check
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get latest release from inotia00/revanced-patches
        id: latest-release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/inotia00/revanced-patches/releases/latest | jq -r '.tag_name')
          echo "::set-output name=tag_name::$LATEST_RELEASE"
      - name: Compare with local version
        run: |
          LOCAL_VERSION=$(cat latest-parsed-version.md)
          if [ "$LOCAL_VERSION" == "${{ steps.latest-release.outputs.tag_name }}" ]; then
            echo "Already up-to-date!"
          else
            echo "Local reported version doesn't match fetched version, updating local version and running new Build action!"
            echo "${{ steps.latest-release.outputs.tag_name }}" > latest-parsed-version.md
            echo "::set-output name=trigger_build::true"
          fi
        id: compare-version
      - name: Trigger build workflow
        if: ${{ steps.compare-version.outputs.trigger_build == 'true' }}
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: "Build & Release" #build-apk.yml
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
