name: Scheduled Update Check
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # hourly
jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get latest release
        id: latest-release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          owner: inotia00
          repo: revanced-patches
      - name: Read latest parsed version
        id: latest-parsed-version
        run: |
          content=`cat latest-parsed-version.md`
          echo "::set-output name=content::$content"
      - name: Compare and update
        if: ${{ steps.latest-release.outputs.tag_name != steps.latest-parsed-version.outputs.content }}
        run: |
          echo "${{ steps.latest-release.outputs.tag_name }}" > latest-parsed-version.md
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add latest-parsed-version.md
          git commit -m "Update latest parsed version"
          git push
      - name: Trigger build APK workflow
        if: ${{ steps.latest-release.outputs.tag_name != steps.latest-parsed-version.outputs.content }}
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: build-apk.yml
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
