name: Selenium Testing

on: #[push]  # Trigger the workflow when code is pushed to the repository
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r apps/scripts/requirements.txt

    - name: Run Selenium script
      run: python apps/tests/seltest.py
