name: Selenium Workflow

on: [push]  # Trigger the workflow when code is pushed to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Checkout the repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Set the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install pyvirtualdisplay

    - name: Run Selenium script
      run: python .github/workflows/test.py  # Replace with the name of your Python file
