name: Update Checker

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main
              
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.11"

      - name: Install python dependencies
        run: pip install -r requirements.txt
 
      # - name: Set user repository
      #   env:
      #     script: scripts/check-updates.py
      #   run: |
      #     sed -i 's@repository =.*@repository = "${{ github.repository }}"@' "$script"

      # - name: Commit updated user repository
      #   uses: stefanzweifel/git-auto-commit-action@master
      #   with:
      #     skip_checkout: true
      #     file_pattern: .
      #     commit_message: 📝 Updated current user repository
        
      - name: Check for updates
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/check-updates.py "${{ github.repository }}"

      - name: Commit Monitored Patches Dl file
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          # Using a different branch to not clutter the default one with the commits.
          # Make sure that your branch doesn't get replaced or deleted otherwise
          # the Update Checker won't work as it should.
          branch: check-updates
          create_branch: true
          skip_checkout: true
          file_pattern: 'scripts/monitored-patches.json'
          commit_options: '--allow-empty'
          commit_message: ⏫ Fetched updates for patches dl
          push_options: '--force'