name: Update Checker
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get latest release from inotia00/revanced-patches
        id: latest-release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/inotia00/revanced-patches/releases/latest | jq -r '.tag_name')
          echo "::set-output name=tag_name::$LATEST_RELEASE"
      - name: Compare with local version
        run: |
          LOCAL_VERSION=$(cat latest-parsed-version.md)
          if [ "$LOCAL_VERSION" == "${{ steps.latest-release.outputs.tag_name }}" ]; then
            echo "Already up-to-date!"
          else
            echo "Local reported version doesn't match fetched version, updating local version and running new Build action!"
            echo "${{ steps.latest-release.outputs.tag_name }}" > latest-parsed-version.md
            git add latest-parsed-version.md
            git commit -m "Update latest-parsed-version.md"
            git push
            echo "::set-output name=trigger_build::true"
          fi
        id: compare-version
      - name: Verify local version update
        if: ${{ steps.compare-version.outputs.trigger_build == 'true' }}
        run: |
          UPDATED_VERSION=$(cat latest-parsed-version.md)
          if [ "$UPDATED_VERSION" == "${{ steps.latest-release.outputs.tag_name }}" ]; then
            echo "Local version updated successfully!"
          else
            echo "Error updating local version, halting workflow!"
            exit 1
          fi
      - name: Trigger build workflow
        if: ${{ steps.compare-version.outputs.trigger_build == 'true' }}
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: "Build & Release" # build-apk.yml
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
